CREATE TYPE etat_emprunt AS ENUM ('en_cour', 'retournee', 'en_retard');

CREATE TABLE TypeMembre
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duree_emprunt_jours INTEGER NOT NULL,
    descriptionn VARCHAR(100) NOT NULL
);

CREATE TABLE Membre
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    telephone VARCHAR(20),
    date_inscription DATE NOT NULL,
    type_membree_id INTEGER NOT NULL REFERENCES TypeMembre (id)
);

CREATE TABLE Document
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR(200) NOT NULL,
    type VARCHAR(50)  NOT NULL,
    annee INTEGER
);

CREATE TABLE RessourceNumerique
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    format_fichier VARCHAR(50) NOT NULL,
    taille_ko INTEGER NOT NULL,
    document_id INTEGER NOT NULL UNIQUE REFERENCES Document (id)
);

CREATE TABLE Emprunt
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_emprunt TIMESTAMP NOT NULL,
    date_retour_prevue TIMESTAMP NOT NULL,
    date_retor_reelle TIMESTAMP,
    etat etat_emprunt NOT NULL,
    membre_id INTEGER NOT NULL REFERENCES Membre (id),
    document_id INTEGER NOT NULL REFERENCES Document (id)
);

CREATE TABLE Reservation
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_reservation TIMESTAMP NOT NULL,
    membre_id INTEGER NOT NULL REFERENCES Membre (id),
    document_id INTEGER   NOT NULL REFERENCES Document (id)
);

CREATE TABLE Amende
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    montant INTEGER NOT NULL,
    payee BOOLEAN NOT NULL,
    membre_id INTEGER NOT NULL REFERENCES Membre (id),
    emprunt_id INTEGER NOT NULL UNIQUE REFERENCES Emprunt (id)
);

CREATE TABLE Auteur
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL
);

CREATE TABLE DocumentAuteur
(
    PRIMARY KEY (document_id, auteur_id),
    document_id INTEGER REFERENCES Document (id),
    auteur_id INTEGER REFERENCES Auteur (id)
);





